development:
  adapter: postgresql
  database: travelist_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: travelist_test

production:
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: travelist_production

  